### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by chorori** [chorori/protospace-39265#1]
#URL
https://protospace-39265.onrender.com

**Comment by chorori** [comment]
> #URL https://protospace-39265.onrender.com

**Comment by snkw-works** [comment]
@chorori さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]
- [x] **新規投稿ページにて、画像は1枚必須であるよう修正しましょう**
画像を選択しなくても保存できてしまいます。

- [x] **ログイン状態のユーザーであっても、他のユーザーのプロトタイプ編集ページのURLを直接入力して遷移しようとすると、トップページにリダイレクトされるよう修正しましょう**
他のユーザーのプロトタイプ編集ページに遷移できてしまいます。

修正が完了しましたら、一度ご自身の本番環境で正しく動作しているか確認してみましょう！
修正内容が反映されていることを確認できましたら、以下のProtoSpace完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by mo1015** [comment]
@chorori さん、お待たせいたしました。ご提出ありがとうございます‼︎
正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉

次はいよいよ最終課題ですね！今まで学習したことを活かして進めていきましょう（^^）
